# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "GLUE_TASKS": "text_classification.ipynb",
         "task": "text_classification.ipynb",
         "model_checkpoint": "text_classification.ipynb",
         "batch_size": "text_classification.ipynb",
         "actual_task": "text_classification.ipynb",
         "dataset": "text_classification.ipynb",
         "metric": "text_classification.ipynb",
         "show_random_elements": "text_classification.ipynb",
         "preprocess_function": "text_classification.ipynb",
         "compute_metrics": "text_classification.ipynb",
         "model_init": "text_classification.ipynb"}

modules = ["core.py",
           "transformers.py"]

doc_url = "https://pyvandenbussche.github.io/nbdev_test/"

git_url = "https://github.com/pyvandenbussche/nbdev_test/tree/master/"

def custom_doc_links(name): return None
